### ISSUE TITLE
Documentations are not updated to reflect quoted strings as parameters

### ISSUE THREAD

**Issue by ranaldmiao** [CS2103-AY1819S1-W17-4/main#156]
Especially so for AttachmentCommand, Import/Export command.

Linked to #148.

(PS: putting here as a reminder)

**Comment by btzy** [comment]
Documentation should also state that if space-separated strings are not quoted, multiple consecutive spaces will be converted to a single space.  Also that non-quoted space-containing strings are discouraged because previously-succeeding commands might silently change behaviour if new prefixes are introduced.

**Comment by btzy** [comment]
This has been resolved by @ranaldmiao.
